# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
  - nodered-cert-le.yaml
  - nodered-cf-external-secrets.yaml
  - nodered-le-prod-issuer.yaml
#  - nodered-le-stg-issuer.yaml
