# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: mqtt
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - service.yaml
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - external-secrets.yaml
#  - vault-secret-store.yaml
  - loadbalancer.yaml
