# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: neuvector
resources:
  - namespace.yaml
#  - neuvector-crd-stack.yaml
  - neuvector-core-stack.yaml
#  - neuvector-monitor-stack.yaml
  - lb.yaml
