# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: neuvector
resources:
  - namespace.yaml
  - neuvector-crd-stack.yaml
  - neuvector-core-stack.yaml
  - neuvector-monitor-stack.yaml
  - lb.yaml
