# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace not specified as it's generated via jsonnet and kustomize will override with namespace mutation errors
resources:
  - alertmanager-alertmanager.yaml
  - alertmanager-secret.yaml
  - alertmanager-service.yaml
  - alertmanager-serviceAccount.yaml
  - alertmanager-serviceMonitor.yaml
  - armexporter-clusterRole.yaml
  - armexporter-clusterRoleBinding.yaml
  - armexporter-daemonset.yaml
  - armexporter-service.yaml
  - armexporter-serviceAccount.yaml
  - armexporter-serviceMonitor.yaml
#  - grafana-config.yaml - now migrated to vault
  - grafana-dashboardDatasources.yaml
  - grafana-dashboardDefinitions.yaml
  - grafana-dashboardSources.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-serviceAccount.yaml
  - grafana-serviceMonitor.yaml
  - grafana-storage.yaml
  - ingress-alertmanager.yaml
  - ingress-grafana.yaml
  - ingress-prometheus.yaml
  - kube-state-metrics-clusterRole.yaml
  - kube-state-metrics-clusterRoleBinding.yaml
  - kube-state-metrics-deployment.yaml
  - kube-state-metrics-service.yaml
  - kube-state-metrics-serviceAccount.yaml
  - kube-state-metrics-serviceMonitor.yaml
  - metallbexporter-clusterRole.yaml
  - metallbexporter-clusterRoleBinding.yaml
  - metallbexporter-service.yaml
  - metallbexporter-serviceMonitor.yaml
  - node-exporter-clusterRole.yaml
  - node-exporter-clusterRoleBinding.yaml
  - node-exporter-daemonset.yaml
  - node-exporter-service.yaml
  - node-exporter-serviceAccount.yaml
  - node-exporter-serviceMonitor.yaml
  - prometheus-adapter-apiService.yaml
  - prometheus-adapter-clusterRole.yaml
  - prometheus-adapter-clusterRoleAggregatedMetricsReader.yaml
  - prometheus-adapter-clusterRoleBinding.yaml
  - prometheus-adapter-clusterRoleBindingDelegator.yaml
  - prometheus-adapter-clusterRoleServerResources.yaml
  - prometheus-adapter-configMap.yaml
  - prometheus-adapter-deployment.yaml
  - prometheus-adapter-roleBindingAuthReader.yaml
  - prometheus-adapter-service.yaml
  - prometheus-adapter-serviceAccount.yaml
  - prometheus-clusterRole.yaml
  - prometheus-clusterRoleBinding.yaml
  - prometheus-kubeControllerManagerPrometheusDiscoveryService.yaml
  - prometheus-kubeDnsPrometheusDiscoveryService.yaml
  - prometheus-kubeSchedulerPrometheusDiscoveryService.yaml
  - prometheus-operator-serviceMonitor.yaml
  - prometheus-prometheus.yaml
  - prometheus-roleBindingConfig.yaml
  - prometheus-roleBindingSpecificNamespaces.yaml
  - prometheus-roleConfig.yaml
  - prometheus-roleSpecificNamespaces.yaml
  - prometheus-rules.yaml
  - prometheus-service.yaml
  - prometheus-serviceAccount.yaml
  - prometheus-serviceMonitor.yaml
  - prometheus-serviceMonitorApiserver.yaml
  - prometheus-serviceMonitorCoreDNS.yaml
  - prometheus-serviceMonitorKubeControllerManager.yaml
  - prometheus-serviceMonitorKubeScheduler.yaml
  - prometheus-serviceMonitorKubelet.yaml
  - cert.yaml
  - cert-issuer.yaml
#  - vault-secret-store.yaml
  - external-secrets.yaml
#  - vault-prometheus-serviceaccount.yaml
#  - vault-servicemonitor.yaml
