# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - cert.yaml
  - cf-external-secret.yaml
  - issuer-prod.yaml
#  - issuer-staging.yaml
