# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frigate
resources:
  - namespace.yaml
  - frigate-stack.yaml
  - serviceaccount.yaml
  - external-secrets.yaml
#  - vault-secret-store.yaml
