# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: torrent
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - external-secrets.yaml
  - vault-secret-store.yaml
  - service.yaml
  - ingress.yaml
  - cert-issuer.yaml
  - cert.yaml
