customRules:
  custom-rules.yaml: |-
    - rule: Contact K8S API Server From Container
      exceptions:
        - name: allow_kube_rbac_proxy_in_monitoring_for_metrics
          fields: [proc.name, k8s.ns.name, k8s.pod.name]
          comps: [=, =, startswith]
          values:
            - [kube-rbac-proxy, monitoring, kube-state-metrics-]
            - [kube-rbac-proxy, monitoring, arm-exporter-]
            - [kube-rbac-proxy, monitoring, node-exporter-]

      override:
        exceptions: append
