# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: unifi-controller
resources:
  - namespace.yaml
  - unifi-stack.yaml
  - unifi-services.yaml
 # - cert.yaml
 # - cert-issuer.yaml
#  - allow-ext-egress-netpol.yaml
#  - allow-local-egress-dns-netpol.yaml
#  - deny-all-egress-netpol.yaml

#patches:
#  - patch-deployment-certs.yaml
