# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: zigbee2mqtt
resources:
  - namespace.yaml
  - stack.yaml
  - loadbalancer.yaml
  - external-secrets.yaml
  - vault-secret-store.yaml
