# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gateway-crds.yaml
  - nginx-crds.yaml
  - nginx-gateway-fabric-stack.yaml
#  - ocirepository.yaml
#  - helmrelease.yaml
